### ISSUE TITLE
[Bug/Feature Request] Unable to open multiple instances

### ISSUE THREAD

**Issue by joker-119** [ALEXWARELLC/tb_app#9]
If the app is open, and you attempt to open another instance of it, it will open a blank window, wait a few seconds, and then close again. 

Ideally, the app should allow multiple instances to be opened, just as multiple windows can be opened from the existing instances.

**Comment by ALEXWARELLC** [comment]
Because of the way the protocol system works, it first looks for the client, but the issue arises when multiple instances of the client are running.

They have an issue where they have started 'fighting' over which instance actions on the protocol url.

I am working on unlocking it and making a more useful system in the long-term.

Electron's Docs are kinda ass though, so I'm very much working on a more scalable solution.

**Comment by ALEXWARELLC** [comment]
I have updated the code to allow for multiple instances. This fix should work. Please let me know if it doesn't work for you.

![image](https://github.com/ALEXWARELLC/tb_app/assets/123724383/462e3e3f-3c78-4c31-9046-8531702339ac)
